In [691]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import random
import math

In [692]:
books = pd.read_csv("./data/books.csv", sep=";", 
                   on_bad_lines="skip", encoding="latin-1")
ratings = pd.read_csv("./data/ratings.csv", sep=";", 
                   on_bad_lines="skip", encoding="latin-1")
users = pd.read_csv("./data/users.csv", sep=";", 
                   on_bad_lines="skip", encoding="latin-1")

C:\Users\Alexander\AppData\Local\Temp\ipykernel_5736\2009980231.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("./data/books.csv", sep=";",

In [693]:
books.columns = ['ISBN', 'bookTitle', 'bookAuthor', 'yearOfPublication', 'publisher', 
                 'imageUrlS', 'imageUrlM', 'imageUrlL']

users.columns = ['userID', 'Location', 'Age']

ratings.columns = ['userID', 'ISBN', 'bookRating']
print(books.head())

         ISBN                                          bookTitle  \
0  0195153448                                Classical Mythology
1  0002005018                                       Clara Callan
2  0060973129                               Decision in Normandy
3  0374157065  Flu: The Story of the Great Influenza Pandemic...
4  0393045218                             The Mummies of Urumchi

             bookAuthor yearOfPublication                   publisher  \
0    Mark P. O. Morford              2002     Oxford University Press
1  Richard Bruce Wright              2001       HarperFlamingo Canada
2          Carlo D'Este              1991             HarperPerennial
3      Gina Bari Kolata              1999        Farrar Straus Giroux
4       E. J. W. Barber              1999  W. W. Norton &amp; Company

                                           imageUrlS  \
0  http://images.amazon.com/images/P/0195153448.0...
1  http://images.amazon.com/images/P/0002005018.0...
2  http://images.amazon.com/images/P/0060973129.0...
3  http://images.amazon.com/images/P/0374157065.0...
4  http://images.amazon.com/images/P/0393045218.0...

                                           imageUrlM  \
0  http://images.amazon.com/images/P/0195153448.0...
1  http://images.amazon.com/images/P/0002005018.0...
2  http://images.amazon.com/images/P/0060973129.0...
3  http://images.amazon.com/images/P/0374157065.0...
4  http://images.amazon.com/images/P/0393045218.0...

                                           imageUrlL
0  http://images.amazon.com/images/P/0195153448.0...
1  http://images.amazon.com/images/P/0002005018.0...
2  http://images.amazon.com/images/P/0060973129.0...
3  http://images.amazon.com/images/P/0374157065.0...
4  http://images.amazon.com/images/P/0393045218.0...

In [694]:
print(ratings.head())

   userID        ISBN  bookRating
0  276725  034545104X           0
1  276726  0155061224           5
2  276727  0446520802           0
3  276729  052165615X           3
4  276729  0521795028           6

In [695]:
print(users.head())

   userID                            Location   Age
0       1                  nyc, new york, usa   NaN
1       2           stockton, california, usa  18.0
2       3     moscow, yukon territory, russia   NaN
3       4           porto, v.n.gaia, portugal  17.0
4       5  farnborough, hants, united kingdom   NaN

In [696]:
print(books.shape)

(271360, 8)

In [697]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ISBN               271360 non-null  object
 1   bookTitle          271360 non-null  object
 2   bookAuthor         271358 non-null  object
 3   yearOfPublication  271360 non-null  object
 4   publisher          271358 non-null  object
 5   imageUrlS          271360 non-null  object
 6   imageUrlM          271360 non-null  object
 7   imageUrlL          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB

In [698]:
books.yearOfPublication.unique()

array([2002, 2001, 1991, 1999, 2000, 1993, 1996, 1988, 2004, 1998, 1994,
       2003, 1997, 1983, 1979, 1995, 1982, 1985, 1992, 1986, 1978, 1980,
       1952, 1987, 1990, 1981, 1989, 1984, 0, 1968, 1961, 1958, 1974,
       1976, 1971, 1977, 1975, 1965, 1941, 1970, 1962, 1973, 1972, 1960,
       1966, 1920, 1956, 1959, 1953, 1951, 1942, 1963, 1964, 1969, 1954,
       1950, 1967, 2005, 1957, 1940, 1937, 1955, 1946, 1936, 1930, 2011,
       1925, 1948, 1943, 1947, 1945, 1923, 2020, 1939, 1926, 1938, 2030,
       1911, 1904, 1949, 1932, 1928, 1929, 1927, 1931, 1914, 2050, 1934,
       1910, 1933, 1902, 1924, 1921, 1900, 2038, 2026, 1944, 1917, 1901,
       2010, 1908, 1906, 1935, 1806, 2021, '2000', '1995', '1999', '2004',
       '2003', '1990', '1994', '1986', '1989', '2002', '1981', '1993',
       '1983', '1982', '1976', '1991', '1977', '1998', '1992', '1996',
       '0', '1997', '2001', '1974', '1968', '1987', '1984', '1988',
       '1963', '1956', '1970', '1985', '1978', '1973', '1980', '1979',
       '1975', '1969', '1961', '1965', '1939', '1958', '1950', '1953',
       '1966', '1971', '1959', '1972', '1955', '1957', '1945', '1960',
       '1967', '1932', '1924', '1964', '2012', '1911', '1927', '1948',
       '1962', '2006', '1952', '1940', '1951', '1931', '1954', '2005',
       '1930', '1941', '1944', 'DK Publishing Inc', '1943', '1938',
       '1900', '1942', '1923', '1920', '1933', 'Gallimard', '1909',
       '1946', '2008', '1378', '2030', '1936', '1947', '2011', '2020',
       '1919', '1949', '1922', '1897', '2024', '1376', '1926', '2037'],
      dtype=object)

In [699]:


books.loc[books.yearOfPublication == 'Gallimard',:]

,ISBN,bookTitle,bookAuthor,yearOfPublication,publisher,imageUrlS,imageUrlM,imageUrlL
220731,2070426769,"Peuple du ciel, suivi de 'Les Bergers\"";Jean-M...",2003,Gallimard,http://images.amazon.com/images/P/2070426769.0...,http://images.amazon.com/images/P/2070426769.0...,http://images.amazon.com/images/P/2070426769.0...,NaN

In [700]:
books.loc[books.yearOfPublication == 'DK Publishing Inc',:]

,ISBN,bookTitle,bookAuthor,yearOfPublication,publisher,imageUrlS,imageUrlM,imageUrlL
209538,078946697X,"DK Readers: Creating the X-Men, How It All Beg...",2000,DK Publishing Inc,http://images.amazon.com/images/P/078946697X.0...,http://images.amazon.com/images/P/078946697X.0...,http://images.amazon.com/images/P/078946697X.0...,NaN
221678,0789466953,"DK Readers: Creating the X-Men, How Comic Book...",2000,DK Publishing Inc,http://images.amazon.com/images/P/0789466953.0...,http://images.amazon.com/images/P/0789466953.0...,http://images.amazon.com/images/P/0789466953.0...,NaN

In [701]:
books = books[(books.yearOfPublication != 'DK Publishing Inc')
              & (books.yearOfPublication != 'Gallimard')]

In [702]:
books.yearOfPublication = books.yearOfPublication.astype('int16')
books.dtypes

ISBN                 object
bookTitle            object
bookAuthor           object
yearOfPublication     int16
publisher            object
imageUrlS            object
imageUrlM            object
imageUrlL            object
dtype: object

In [703]:
books = books.dropna(subset=['publisher'])
books.publisher.isnull().sum()

0

In [704]:
print(books.loc[books.yearOfPublication >=2024,:])

              ISBN                                          bookTitle  \
37487   0671746103  MY TEACHER FRIED MY BRAINS (RACK SIZE) (MY TEA...
55676   0671791990  MY TEACHER FLUNKED THE PLANET (RACK SIZE) (MY ...
78168   0870449842                                   Crossing America
80264   0140301690  Alice's Adventures in Wonderland and Through t...
97826   0140201092      Outline of European Architecture (Pelican S.)
116053  0394701658                       Three Plays of Eugene Oneill
118294  3442436893        Das groÃ?Â?e BÃ?Â¶se- MÃ?Â¤dchen- Lesebuch.
192993  0870446924  Field Guide to the Birds of North America, 3rd...
228173  0671266500       FOREST PEOPLE (Touchstone Books (Hardcover))
240169  0684718022            In Our Time: Stories (Scribner Classic)
246842  0380000059                                              CLOUT
255409  068471809X                               To Have and Have Not
260974  0671740989        FOOTBALL SUPER TEAMS : FOOTBALL SUPER TEAMS

                         bookAuthor  yearOfPublication  \
37487                       Coville               2030
55676                 Bruce Coville               2030
78168   National Geographic Society               2030
80264                 Lewis Carroll               2050
97826              Nikolaus Pevsner               2050
116053               Eugene O'Neill               2038
118294                  Kathy Lette               2026
192993  National Geographic Society               2030
228173            Colin M. Turnbull               2030
240169             Ernest Hemingway               2030
246842                   D. GIBBONS               2024
255409             Ernest Hemingway               2037
260974                  Bill Gutman               2030

                                         publisher  \
37487                                      Aladdin
55676                                      Aladdin
78168                          National Geographic
80264                                 Puffin Books
97826                                  Penguin USA
116053                           Vintage Books USA
118294                                    Goldmann
192993                         National Geographic
228173                        Simon &amp; Schuster
240169                               Collier Books
246842                                        Avon
255409                        Simon &amp; Schuster
260974  Simon &amp; Schuster Children's Publishing

                                                imageUrlS  \
37487   http://images.amazon.com/images/P/0671746103.0...
55676   http://images.amazon.com/images/P/0671791990.0...
78168   http://images.amazon.com/images/P/0870449842.0...
80264   http://images.amazon.com/images/P/0140301690.0...
97826   http://images.amazon.com/images/P/0140201092.0...
116053  http://images.amazon.com/images/P/0394701658.0...
118294  http://images.amazon.com/images/P/3442436893.0...
192993  http://images.amazon.com/images/P/0870446924.0...
228173  http://images.amazon.com/images/P/0671266500.0...
240169  http://images.amazon.com/images/P/0684718022.0...
246842  http://images.amazon.com/images/P/0380000059.0...
255409  http://images.amazon.com/images/P/068471809X.0...
260974  http://images.amazon.com/images/P/0671740989.0...

                                                imageUrlM  \
37487   http://images.amazon.com/images/P/0671746103.0...
55676   http://images.amazon.com/images/P/0671791990.0...
78168   http://images.amazon.com/images/P/0870449842.0...
80264   http://images.amazon.com/images/P/0140301690.0...
97826   http://images.amazon.com/images/P/0140201092.0...
116053  http://images.amazon.com/images/P/0394701658.0...
118294  http://images.amazon.com/images/P/3442436893.0...
192993  http://images.amazon.com/images/P/0870446924.0...
228173  http://images.amazon.com/images/P/0671266500.0...
240169  http://images.amazon.com/images/P/0684718022.0...
246842  http://images.amazon.com/images/P/0380000059.0...
255409  http://images.amazon.com/images/P/068471809X.0...
260974  http://images.amazon.com/images/P/0671740989.0...

                                                imageUrlL
37487   http://images.amazon.com/images/P/0671746103.0...
55676   http://images.amazon.com/images/P/0671791990.0...
78168   http://images.amazon.com/images/P/0870449842.0...
80264   http://images.amazon.com/images/P/0140301690.0...
97826   http://images.amazon.com/images/P/0140201092.0...
116053  http://images.amazon.com/images/P/0394701658.0...
118294  http://images.amazon.com/images/P/3442436893.0...
192993  http://images.amazon.com/images/P/0870446924.0...
228173  http://images.amazon.com/images/P/0671266500.0...
240169  http://images.amazon.com/images/P/0684718022.0...
246842  http://images.amazon.com/images/P/0380000059.0...
255409  http://images.amazon.com/images/P/068471809X.0...
260974  http://images.amazon.com/images/P/0671740989.0...

In [705]:
print(books.loc[books.yearOfPublication == 0,:])

              ISBN                                          bookTitle  \
176     3150000335                                   Kabale Und Liebe
188     342311360X                            Die Liebe in Den Zelten
288     0571197639                        Poisonwood Bible Edition Uk
351     3596214629       Herr Der Fliegen (Fiction, Poetry and Drama)
542     8845229041  Biblioteca Universale Rizzoli: Sulla Sponda De...
...            ...                                                ...
270794  014029953X                         Foe (Essential.penguin S.)
270913  0340571187                                     Postmens House
271094  8427201079                           El Misterio De Sittaford
271182  0887781721                                          Tom Penny
271196  3150013763                                     Der Hofmeister

                    bookAuthor  yearOfPublication  \
176                   Schiller                  0
188     Gabriel Garcia Marquez                  0
288         Barbara Kingsolver                  0
351                    Golding                  0
542                   P Coelho                  0
...                        ...                ...
270794            J.M. Coetzee                  0
270913        Maggie Hemingway                  0
271094         Agatha Christie                  0
271182             Tony German                  0
271196              Jakob Lenz                  0

                                 publisher  \
176        Philipp Reclam, Jun Verlag GmbH
188     Deutscher Taschenbuch Verlag (DTV)
288                        Faber Faber Inc
351        Fischer Taschenbuch Verlag GmbH
542                     Fabbri - RCS Libri
...                                    ...
270794                   Penguin Books Ltd
270913                    Trafalgar Square
271094                    Editorial Molino
271182                P. Martin Associates
271196     Philipp Reclam, Jun Verlag GmbH

                                                imageUrlS  \
176     http://images.amazon.com/images/P/3150000335.0...
188     http://images.amazon.com/images/P/342311360X.0...
288     http://images.amazon.com/images/P/0571197639.0...
351     http://images.amazon.com/images/P/3596214629.0...
542     http://images.amazon.com/images/P/8845229041.0...
...                                                   ...
270794  http://images.amazon.com/images/P/014029953X.0...
270913  http://images.amazon.com/images/P/0340571187.0...
271094  http://images.amazon.com/images/P/8427201079.0...
271182  http://images.amazon.com/images/P/0887781721.0...
271196  http://images.amazon.com/images/P/3150013763.0...

                                                imageUrlM  \
176     http://images.amazon.com/images/P/3150000335.0...
188     http://images.amazon.com/images/P/342311360X.0...
288     http://images.amazon.com/images/P/0571197639.0...
351     http://images.amazon.com/images/P/3596214629.0...
542     http://images.amazon.com/images/P/8845229041.0...
...                                                   ...
270794  http://images.amazon.com/images/P/014029953X.0...
270913  http://images.amazon.com/images/P/0340571187.0...
271094  http://images.amazon.com/images/P/8427201079.0...
271182  http://images.amazon.com/images/P/0887781721.0...
271196  http://images.amazon.com/images/P/3150013763.0...

                                                imageUrlL
176     http://images.amazon.com/images/P/3150000335.0...
188     http://images.amazon.com/images/P/342311360X.0...
288     http://images.amazon.com/images/P/0571197639.0...
351     http://images.amazon.com/images/P/3596214629.0...
542     http://images.amazon.com/images/P/8845229041.0...
...                                                   ...
270794  http://images.amazon.com/images/P/014029953X.0...
270913  http://images.amazon.com/images/P/0340571187.0...
271094  http://images.amazon.com/images/P/8427201079.0...
271182  http://images.amazon.com/images/P/0887781721.0...
271196  http://images.amazon.com/images/P/3150013763.0...

[4618 rows x 8 columns]

In [706]:
books = books[(books.yearOfPublication <=2024)
              & (books.yearOfPublication >= 1000)]

In [707]:
print(books.loc[books.yearOfPublication == 0,:])

Empty DataFrame
Columns: [ISBN, bookTitle, bookAuthor, yearOfPublication, publisher, imageUrlS, imageUrlM, imageUrlL]
Index: []

In [708]:
books.duplicated(subset='bookTitle').sum() # 29,225

28226

In [709]:
books = books.drop_duplicates(subset='bookTitle')

In [710]:
books.duplicated(subset='bookTitle').sum()

0

In [711]:
ratings_new = ratings[ratings.ISBN.isin(books.ISBN)]
x = ratings['userID'].value_counts() > 200
y = x[x].index
ratings = ratings[ratings['userID'].isin(y)]
rating_with_books = ratings.merge(books, on='ISBN')
rating_with_books

,userID,ISBN,bookRating,bookTitle,bookAuthor,yearOfPublication,publisher,imageUrlS,imageUrlM,imageUrlL
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1,3363,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
2,11676,002542730X,6,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
3,12538,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
4,13552,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
...,...,...,...,...,...,...,...,...,...,...
417068,275970,1892145022,0,Here Is New York,E. B. White,1999,Little Bookroom,http://images.amazon.com/images/P/1892145022.0...,http://images.amazon.com/images/P/1892145022.0...,http://images.amazon.com/images/P/1892145022.0...
417069,275970,1931868123,0,There's a Porcupine in My Outhouse: Misadventu...,Mike Tougias,2002,Capital Books (VA),http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...,http://images.amazon.com/images/P/1931868123.0...
417070,275970,3411086211,10,Die Biene.,Sybil GrÃ?Â¤fin SchÃ?Â¶nfeldt,1993,"Bibliographisches Institut, Mannheim",http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...,http://images.amazon.com/images/P/3411086211.0...
417071,275970,3829021860,0,The Penis Book,Joseph Cohen,1999,Konemann,http://images.amazon.com/images/P/3829021860.0...,http://images.amazon.com/images/P/3829021860.0...,http://images.amazon.com/images/P/3829021860.0...
417072,275970,4770019572,0,Musashi,Eiji Yoshikawa,1995,Kodansha International (JPN),http://images.amazon.com/images/P/4770019572.0...,http://images.amazon.com/images/P/4770019572.0...,http://images.amazon.com/images/P/4770019572.0...

In [712]:
number_rating = rating_with_books.groupby('bookTitle')['bookRating'].count().reset_index()
number_rating.rename(columns= {'bookRating':'number_of_ratings'}, inplace=True)
number_rating

                                                bookTitle  number_of_ratings
0        A Light in the Storm: The Civil War Diary of ...                  2
1                                   Always Have Popsicles                  1
2                    Apple Magic (The Collector's series)                  1
3        Beyond IBM: Leadership Marketing and Finance ...                  1
4        Clifford Visita El Hospital (Clifford El Gran...                  1
...                                                   ...                ...
155763  Ã?Â?ber die Pflicht zum Ungehorsam gegen den S...                  3
155764                                      Ã?Â?lpiraten.                  1
155765                     Ã?Â?rger mit Produkt X. Roman.                  1
155766                              Ã?Â?stlich der Berge.                  1
155767                                  Ã?Â?thique en toc                  1

[155768 rows x 2 columns]

In [713]:
avg_ratings = rating_with_books.groupby('bookTitle')['bookRating'].mean().reset_index()
avg_ratings.head()

                                           bookTitle  bookRating
0   A Light in the Storm: The Civil War Diary of ...         4.5
1                              Always Have Popsicles         0.0
2               Apple Magic (The Collector's series)         0.0
3   Beyond IBM: Leadership Marketing and Finance ...         0.0
4   Clifford Visita El Hospital (Clifford El Gran...         0.0

In [714]:
final_rating = rating_with_books.merge(number_rating, on='bookTitle')

In [715]:
final_rating = final_rating[final_rating['number_of_ratings'] >= 40]
final_rating.drop_duplicates(['userID','bookTitle'], inplace=True)

In [716]:
final_rating

,userID,ISBN,bookRating,bookTitle,bookAuthor,yearOfPublication,publisher,imageUrlS,imageUrlM,imageUrlL,number_of_ratings
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,80
1,3363,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,80
2,11676,002542730X,6,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,80
3,12538,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,80
4,13552,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,80
...,...,...,...,...,...,...,...,...,...,...,...
221082,241980,0671759345,10,Ruby (Landry),V.C. Andrews,1994,Pocket,http://images.amazon.com/images/P/0671759345.0...,http://images.amazon.com/images/P/0671759345.0...,http://images.amazon.com/images/P/0671759345.0...,44
221083,245963,0671759345,0,Ruby (Landry),V.C. Andrews,1994,Pocket,http://images.amazon.com/images/P/0671759345.0...,http://images.amazon.com/images/P/0671759345.0...,http://images.amazon.com/images/P/0671759345.0...,44
221084,250962,0671759345,0,Ruby (Landry),V.C. Andrews,1994,Pocket,http://images.amazon.com/images/P/0671759345.0...,http://images.amazon.com/images/P/0671759345.0...,http://images.amazon.com/images/P/0671759345.0...,44
221085,251613,0671759345,0,Ruby (Landry),V.C. Andrews,1994,Pocket,http://images.amazon.com/images/P/0671759345.0...,http://images.amazon.com/images/P/0671759345.0...,http://images.amazon.com/images/P/0671759345.0...,44
221086,259629,0671759345,0,Ruby (Landry),V.C. Andrews,1994,Pocket,http://images.amazon.com/images/P/0671759345.0...,http://images.amazon.com/images/P/0671759345.0...,http://images.amazon.com/images/P/0671759345.0...,44

In [717]:
list_of_distinct_users = list(final_rating['userID'].unique())
print(len(list_of_distinct_users))

884

In [718]:

df = books[books.ISBN.isin(final_rating.ISBN)]

df = df.reset_index()
df = df.drop('index',axis=1)
sampleBooks = df.copy()

In [719]:
sampleBooks

,ISBN,bookTitle,bookAuthor,yearOfPublication,publisher,imageUrlS,imageUrlM,imageUrlL
0,0440234743,The Testament,John Grisham,1999,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...
1,0452264464,Beloved (Plume Contemporary Fiction),Toni Morrison,1994,Plume,http://images.amazon.com/images/P/0452264464.0...,http://images.amazon.com/images/P/0452264464.0...,http://images.amazon.com/images/P/0452264464.0...
2,0971880107,Wild Animus,Rich Shapero,2004,Too Far,http://images.amazon.com/images/P/0971880107.0...,http://images.amazon.com/images/P/0971880107.0...,http://images.amazon.com/images/P/0971880107.0...
3,0345402871,Airframe,Michael Crichton,1997,Ballantine Books,http://images.amazon.com/images/P/0345402871.0...,http://images.amazon.com/images/P/0345402871.0...,http://images.amazon.com/images/P/0345402871.0...
4,0345417623,Timeline,MICHAEL CRICHTON,2000,Ballantine Books,http://images.amazon.com/images/P/0345417623.0...,http://images.amazon.com/images/P/0345417623.0...,http://images.amazon.com/images/P/0345417623.0...
...,...,...,...,...,...,...,...,...
680,1551669293,204 Rosewood Lane,Debbie Macomber,2002,Mira,http://images.amazon.com/images/P/1551669293.0...,http://images.amazon.com/images/P/1551669293.0...,http://images.amazon.com/images/P/1551669293.0...
681,0425137562,Silent Prey,John Sandford,2000,Berkley Publishing Group,http://images.amazon.com/images/P/0425137562.0...,http://images.amazon.com/images/P/0425137562.0...,http://images.amazon.com/images/P/0425137562.0...
682,0515135739,Eleventh Hour: An FBI Thriller (FBI Thriller (...,Catherine Coulter,2004,Jove Books,http://images.amazon.com/images/P/0515135739.0...,http://images.amazon.com/images/P/0515135739.0...,http://images.amazon.com/images/P/0515135739.0...
683,0743418131,Deck the Halls (Holiday Classics),Mary Higgins Clark,2002,Pocket,http://images.amazon.com/images/P/0743418131.0...,http://images.amazon.com/images/P/0743418131.0...,http://images.amazon.com/images/P/0743418131.0...
684,0553290789,Genuine Lies,Nora Roberts,1999,Bantam,http://images.amazon.com/images/P/0553290789.0...,http://images.amazon.com/images/P/0553290789.0...,http://images.amazon.com/images/P/0553290789.0...

In [720]:
sampleBooks =sampleBooks.merge(avg_ratings,on='bookTitle')
sampleBooks['bookRating'] =np.ceil(sampleBooks['bookRating'])

## РЕКОМЕНДАЦИЯ ПО РЕЙТИНГУ ЮЗЕРОВ

In [721]:
from surprise import Reader, Dataset, SVD

In [722]:

reader = Reader(rating_scale=(1, 10))
data   = Dataset.load_from_df(final_rating[['userID','bookTitle','bookRating']], reader)
trainset = data.build_full_trainset()
model = SVD(n_factors=50, n_epochs=10, lr_all=0.005, reg_all= 0.2)
model.fit(trainset)

In [723]:
def generate_recommendationsSVD(userID=277427, get_recommend =10):
    
    
    # predict rating for all pairs of users & items that are not in the trainset
    
    testset = trainset.build_anti_testset()
    predictions = model.test(testset)
    predictions_df = pd.DataFrame(predictions)

    # get the top get_recommend predictions for userID
    
    predictions_userID = predictions_df[predictions_df['uid'] == userID].\
                         sort_values(by="est", ascending = False).head(get_recommend)
    recommendations = []
    recommendations.append(list(predictions_userID['iid']))
    recommendations = recommendations[0]
    rec_books = sampleBooks[sampleBooks.bookTitle.isin(recommendations)]
    return(rec_books.to_dict('records'))

In [724]:
from surprise.model_selection import cross_validate
cross_validate(model, data, measures=['RMSE', 'MAE'], cv=3, verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 3 split(s).

                  Fold 1  Fold 2  Fold 3  Mean    Std
RMSE (testset)    3.2418  3.2499  3.2549  3.2489  0.0054
MAE (testset)     2.6220  2.6245  2.6272  2.6246  0.0021
Fit time          0.07    0.10    0.10    0.09    0.01
Test time         0.05    0.05    0.05    0.05    0.00

{'test_rmse': array([3.24182575, 3.24986439, 3.25492294]),
 'test_mae': array([2.62201147, 2.62454709, 2.62722059]),
 'fit_time': (0.07367277145385742, 0.09878134727478027, 0.09777069091796875),
 'test_time': (0.05232834815979004, 0.04646158218383789, 0.047369956970214844)}

In [725]:
recommendationsSVD = generate_recommendationsSVD(userID=241980, get_recommend =30)

## РЕКОМЕНДАЦИЯ ПО НАЗВАНИЮ, АВТОРУ И ИЗДАТЕЛЮ

In [726]:
def clean_text(author):
    result = str(author).lower()
    return(result.replace(' ',''))

In [727]:
df['bookAuthor'] = df['bookAuthor'].apply(clean_text)

In [728]:
print(sampleBooks['bookTitle'].head())

0                           The Testament
1    Beloved (Plume Contemporary Fiction)
2                             Wild Animus
3                                Airframe
4                                Timeline
Name: bookTitle, dtype: object

In [729]:
df['bookTitle'] = df['bookTitle'].str.lower()
df['publisher'] = df['publisher'].str.lower()

In [730]:
# combine all strings:
df2 = df.drop(['ISBN','imageUrlS','imageUrlM','imageUrlL','yearOfPublication'],axis=1)

df2['data'] = df2[df2.columns[0:]].apply(
    lambda x: ' '.join(x.dropna().astype(str)),
    axis=1
)

df2

,bookTitle,bookAuthor,publisher,data
0,the testament,johngrisham,dell,the testament johngrisham dell
1,beloved (plume contemporary fiction),tonimorrison,plume,beloved (plume contemporary fiction) tonimorri...
2,wild animus,richshapero,too far,wild animus richshapero too far
3,airframe,michaelcrichton,ballantine books,airframe michaelcrichton ballantine books
4,timeline,michaelcrichton,ballantine books,timeline michaelcrichton ballantine books
...,...,...,...,...
680,204 rosewood lane,debbiemacomber,mira,204 rosewood lane debbiemacomber mira
681,silent prey,johnsandford,berkley publishing group,silent prey johnsandford berkley publishing group
682,eleventh hour: an fbi thriller (fbi thriller (...,catherinecoulter,jove books,eleventh hour: an fbi thriller (fbi thriller (...
683,deck the halls (holiday classics),maryhigginsclark,pocket,deck the halls (holiday classics) maryhigginsc...
684,genuine lies,noraroberts,bantam,genuine lies noraroberts bantam

In [731]:
df2['data'][2]

'wild animus richshapero too far'

In [732]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
vectorized = vectorizer.fit_transform(df2['data'])

In [733]:
from sklearn.metrics.pairwise import cosine_similarity

similarities = cosine_similarity(vectorized)

In [734]:
print(similarities)

[[1.         0.         0.         ... 0.         0.18898224 0.        ]
 [0.         1.         0.         ... 0.         0.         0.        ]
 [0.         0.         1.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 1.         0.         0.        ]
 [0.18898224 0.         0.         ... 0.         1.         0.        ]
 [0.         0.         0.         ... 0.         0.         1.        ]]

In [735]:
df = pd.DataFrame(similarities, columns=df['bookTitle'], index=df['bookTitle']).reset_index()

df

bookTitle,bookTitle,the testament,beloved (plume contemporary fiction),wild animus,airframe,timeline,to kill a mockingbird,seabiscuit: an american legend,i'll be seeing you,from the corner of his eye,...,between friends,"morning, noon &amp; night",palomino,m is for malice,vital signs,204 rosewood lane,silent prey,eleventh hour: an fbi thriller (fbi thriller (jove paperback)),deck the halls (holiday classics),genuine lies
0,the testament,1.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.166667,...,0.000000,0.000000,0.288675,0.000000,0.0,0.0,0.0,0.000000,0.188982,0.0
1,beloved (plume contemporary fiction),0.000000,1.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
2,wild animus,0.000000,0.0,1.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,0.0
3,airframe,0.000000,0.0,0.0,1.000000,0.750000,0.0,0.377964,0.000000,0.166667,...,0.223607,0.188982,0.000000,0.204124,0.0,0.0,0.0,0.117851,0.000000,0.0
4,timeline,0.000000,0.0,0.0,0.750000,1.000000,0.0,0.377964,0.000000,0.166667,...,0.223607,0.188982,0.000000,0.204124,0.0,0.0,0.0,0.117851,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
680,204 rosewood lane,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.400000,0.000000,0.000000,0.000000,0.0,1.0,0.0,0.000000,0.000000,0.0
681,silent prey,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.5,0.0,1.0,0.000000,0.000000,0.0
682,eleventh hour: an fbi thriller (fbi thriller (...,0.000000,0.0,0.0,0.117851,0.117851,0.0,0.178174,0.000000,0.078567,...,0.105409,0.089087,0.000000,0.096225,0.0,0.0,0.0,1.000000,0.000000,0.0
683,deck the halls (holiday classics),0.188982,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.308607,0.125988,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,1.000000,0.0
684,genuine lies,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.166667,...,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.000000,0.000000,1.0

In [736]:
booksDict = sampleBooks.to_dict('records')

In [737]:
def get_RecBooks_COSIAN(title):
    recBooks = []

    recommendations = pd.DataFrame(df.nlargest(11,title.lower())['bookTitle'])
    recommendations = recommendations[recommendations['bookTitle']!=title.lower()]
    recList = recommendations['bookTitle'].values.tolist()
    for i in range(len(recList)):
        recBooks.append(sampleBooks[sampleBooks['bookTitle'].str.lower() ==recList[i]].to_dict('records')[0])

    return recBooks

In [742]:
amount_of_books = 12

In [739]:
from flask import Flask, request, jsonify
from flask_cors import CORS, cross_origin
app = Flask(__name__)
cors = CORS(app)
app.config['CORS_HEADERS'] = 'Content-Type'

In [740]:

@app.route('/books')
@cross_origin()
def books():
    amount = len(booksDict)
    pages =math.ceil(amount/amount_of_books-1)
    page = request.args.get('page')
    if not page:
        return jsonify({'books':booksDict[0:amount_of_books],'pages':pages,'page':1}),200
    if int(page)*amount_of_books >len(booksDict):
        return jsonify({'error':'error'}),404
    return jsonify({'books':booksDict[(int(page))*amount_of_books:(int(page)+1)*amount_of_books],'pages':pages,'page':int(page)}),200



@app.route('/books/<id>')
@cross_origin()
def get_one_book(id):
    book = sampleBooks[sampleBooks.ISBN == str(id)].to_dict('records')
    if not book:
        return jsonify({'error':'not found','status':404}),200
    
    return jsonify({'body':book[0],'status':200}),200

@app.route('/get_r_user')
@cross_origin()
def get_r_user():
    random_user = random.randint(0,len(list_of_distinct_users))
    return jsonify({'body':{'userID':int(list_of_distinct_users[random_user])},'status':200}),200


@app.route('/rec_book')
@cross_origin()
def reccomendation_for_book():
    title = request.args.get('title')
    book =sampleBooks[sampleBooks.bookTitle == title].to_dict('records')
    
    if not title:
        return jsonify({'error':'not found','status':404}),200
    elif not book:
        return jsonify({'error':'not found','status':404}),200
    
    recBooks = get_RecBooks_COSIAN(title)
    
    return jsonify({'body':recBooks,'status':200}),200


@app.route('/rec_user')
@cross_origin()
def reccomendation_for_user():
    userID = request.args.get('userID')
    if not int(userID) in list_of_distinct_users:
        return jsonify({'error':'not found','status':404}),200
    
    recBooks = generate_recommendationsSVD(int(userID))
    print(recBooks)
    return jsonify({'body':recBooks,'status':200}),200

In [741]:

if __name__ == '__main__':
    app.run(debug=False)

 * Serving Flask app '__main__'
 * Debug mode: off

WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
127.0.0.1 - - [25/Oct/2023 15:41:08] "GET /books?page=17 HTTP/1.1" 200 -
127.0.0.1 - - [25/Oct/2023 15:45:36] "GET /books?page=18 HTTP/1.1" 200 -
127.0.0.1 - - [25/Oct/2023 15:49:50] "GET /books?page=19 HTTP/1.1" 200 -
127.0.0.1 - - [25/Oct/2023 15:52:08] "GET /books?page=19 HTTP/1.1" 200 -
127.0.0.1 - - [25/Oct/2023 15:53:08] "GET /books?page=22 HTTP/1.1" 200 -
127.0.0.1 - - [25/Oct/2023 15:53:17] "GET /books?page=21 HTTP/1.1" 200 -
127.0.0.1 - - [25/Oct/2023 15:53:23] "GET /books?page=20 HTTP/1.1" 200 -
127.0.0.1 - - [25/Oct/2023 15:53:24] "GET /books?page=18 HTTP/1.1" 200 -
127.0.0.1 - - [25/Oct/2023 15:53:25] "GET /books?page=1 HTTP/1.1" 200 -